[GLOBAL]
pants_version = "2.16.0"

backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.typecheck.mypy",
  "pants.backend.python.lint.isort",
  "pants.backend.python.lint.flake8",
  'pants.backend.docker',
  "pants.backend.shell",
]

[source]
root_patterns = ["/"]

[python]
interpreter_constraints = ["==3.11.4"]
enable_resolves = true

[flake8]
args = ["--output-file=reports/report.txt"]

[docker]
env_vars = ["HOME", "USER", "PATH", "GIT_COMMIT"]

[cli.alias]
green = "fmt lint check"
container-network-create = 'create-dev-network'
container-client = 'run src/docker/client:run-container'
container-server = 'run src/docker/server:run-container'
