[GLOBAL]
pants_version = "2.16.0"

backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
]

[source]
root_patterns = ["/"]

[python]
interpreter_constraints = ["==3.9.*"]