[GLOBAL]
pants_version = "2.16.0"

backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.typecheck.mypy",
  "pants.backend.python.lint.isort",
  "pants.backend.python.lint.flake8",
  'pants.backend.docker',
  "pants.backend.shell",
]

[source]
root_patterns = ["/"]

[python]
interpreter_constraints = ["==3.11.4"]
enable_resolves = true

[flake8]
args = ["--output-file=reports/report.txt"]

[docker]
env_vars = ["HOME", "USER", "PATH", "GIT_COMMIT"]

[cli.alias]
green = "fmt lint check"
# Run the binaries locally on the machine
local-api = "run src/python/api:binary"
local-processor = "run src/python/processor:binary"
# Creates the docker network needed for the containers to communicate
container-network-create = 'create-dev-network'
## These targets run the containerized verison of the application
container-api = 'run src/docker/api:run-container'
container-processor = 'run src/docker/processor:run-container'
