[GLOBAL]
pants_version = "2.16.0"

backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.typecheck.mypy",
  "pants.backend.python.lint.isort",
  "pants.backend.python.lint.flake8",
  'pants.backend.docker',
]

[source]
root_patterns = ["/"]

[python]
interpreter_constraints = ["==3.11.4"]
enable_resolves = true

[flake8]
args = ["--output-file=reports/report.txt"]

[docker]
env_vars = ["HOME", "USER", "PATH", "GIT_COMMIT"]

[cli.alias]
green = "fmt lint check"
client = 'run --docker-run-args="-p 8080:8080 --network=pants-bridge --name client-container -d" src/docker/client:client-container'
server = 'run --docker-run-args="--network=pants-bridge --name server-container -d" src/docker/server:server-container'
