[GLOBAL]
pants_version = "2.16.0"

backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.typecheck.mypy",
  "pants.backend.python.lint.isort",
  "pants.backend.python.lint.flake8",
  'pants.backend.docker',
]

[source]
root_patterns = ["/"]

[python]
interpreter_constraints = ["==3.11.4"]
enable_resolves = true

[python.resolves_to_no_binary]
__default__ = ["pyzmq"]

[flake8]
args = ["--output-file=reports/report.txt"]

[docker]
env_vars = ["HOME", "USER", "PATH", "GIT_COMMIT"]

[dockerfile-parser]
lockfile = "3rdparty/docker/default.lock"
interpreter_constraints = ["==3.11.4"]


[pex]
executable_search_paths = ["<PYENV>"]

# [pex_binaries]


# [python.resolves]
# myresolve = "mylockfile"
