# Since we are building the binary outside of the container and ZeroMQ
# uses a librtary with a native binary, we need to tell Pex which libraries
# it should use from the wheel.
file(name="platforms", source="./platforms.json")
